apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hospital-app
  template:
    metadata:
      labels:
        app: hospital-app
    spec:
      containers:
        - name: hospital-app
          image: muhumuzaivan/hospital-app:latest
          ports:
            - containerPort: 8080