version: '3'
services:
  app:
    image: hospital-app
    build:
      context: .
    ports:
      - "8082:8080"
    depends_on:
      - redis
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/hospital
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
